apiVersion: v1
kind: ReplicationController
metadata:
  name: helloworld-controller
spec:
  replicas: 3
  selector:
    app: docker-get-started
  template:
    metadata:
      labels:
        app: docker-get-started
    spec:
      containers:
      - name: docker-get-started
        image: amitvashist7/k8s-tiny-web
        imagePullPolicy: IfNotPresent
        ports:
        - name: nodejs-port
          containerPort: 80
