apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-3-deployment
  labels:
    app: helloworld-3
spec:
  replicas: 10
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: helloworld-3
  template:
    metadata:
      labels:
        app: helloworld-3
    spec:
      containers:
      - name: k8s-demo
        image: amitvashist7/k8s-tiny-web
        imagePullPolicy: IfNotPresent
        ports:
        - name: node-port
          containerPort: 80

