apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment-2
  labels:
    app: helloworld-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld-2
  template:
    metadata:
      labels:
        app: helloworld-2
    spec:
      containers:
      - name: k8s-demo
        image: amitvashist7/k8s-tiny-web
        imagePullPolicy: IfNotPresent
        ports:
        - name: nodejs-port
          containerPort: 80
      nodeSelector:
        hardware: virtual
        env: prod
