apiVersion: apps/v1
kind: Deployment
metadata:
  name: toleration-3-deployment
  labels:
    app: toleration-3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: toleration-3
  template:
    metadata:
      labels:
        app: toleration-3
    spec:
      containers:
      - name: k8s-demo
        image: amitvashist7/k8s-tiny-web
        ports:
        - name: node-port
          containerPort: 80
      tolerations:
      - key: "app"
        operator: "Equal"
        value: "myapp"
        effect: "NoSchedule"
      - key: "example"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "example2"
        operator: "Equal"
        value: "example2-key"
        effect: "NoExecute"
