apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: helloworld-statefull
  labels:
    app: helloworld
spec:
  serviceName: helloworld-statefull
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: k8s-demo
        image: amitvashist7/k8s-tiny-web
        ports:
        - name: node-port
          containerPort: 80
